#!/bin/sh

#

#    00-header - create the header of the MOTD

#    Copyright (c) 2014 Northern Signal

#

figlet "SignalOS"

printf "\n"

printf "This is "$(hostname)

printf "\n"

printf "\n"

printf "SignalOS 2.0"

printf "\n"

printf "(c) 2014-2016 Northern Signal, All Rights Reserved."

printf "\n"

printf "\n"

date=`date`

load=`cat /proc/loadavg | awk '{print $1}'`

root_usage=`df -h / | awk '/\// {print $(NF-1)}'`

memory_usage=`free -m | awk '/Mem/ { printf("%3.1f%%", $3/$2*100) }'`

swap_usage=`free -m | awk '/Swap/ { printf("%3.1f%%", $3/$2*100) }'`

users=`users | wc -w`

process=`ps -fe | wc -l`

ipadd=`/sbin/ifconfig eth0 | grep "inet addr" | grep -v "127.0.0.1" | awk '{ print $2 }' | awk -F: '{ print $2 }'`

utime=`awk '{print int($1/86400)":"int($1%86400/3600)":"int(($1%3600)/60)":"int($1%60)}' /proc/uptime`

echo "System information as of: $date"

echo

printf "System load:\t%s\t\tMemory usage:\t%s\n" $load $memory_usage

printf "Usage on /:\t%s\t\tSwap usage:\t%s\n" $root_usage $swap_usage

printf "Local users:\t%s\t\tProcesses:\t%s\n" $users $process

printf "IP Address:\t%s\tSystem uptime:\t%s\n" $ipadd $utime

echo
